# Generated by Django 5.0.2 on 2024-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pet_delete_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=50)),
                ('hnumber', models.CharField(default='-', max_length=20)),
                ('hmail', models.CharField(default='hospital@gmail.com', max_length=500)),
                ('hname', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='owner_name',
            new_name='appointmentType',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='pet_name',
            new_name='patient_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pet_gender',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='health_issue',
            field=models.CharField(max_length=1000),
        ),
    ]
