# Generated by Django 5.0.2 on 2024-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date_time',
            field=models.DateField(),
        ),
    ]
