# Generated by Django 5.0.2 on 2024-03-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_doctor_id_alter_doctor_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(default='x@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='ownermail',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
