# Generated by Django 5.0.2 on 2024-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_patient_email_alter_pet_ownermail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ownermail',
            field=models.EmailField(max_length=254),
        ),
    ]
