# Generated by Django 5.0.2 on 2024-03-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_appointment_patient_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='Appointment1',
        ),
    ]
