# Generated by Django 5.0.2 on 2024-03-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_appointment_appointment1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment1',
            name='hospital',
        ),
    ]
