# Generated by Django 5.0.2 on 2024-03-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_appointment1_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment1',
            name='hospital',
            field=models.CharField(default='hospital', max_length=255),
        ),
    ]
