# Generated by Django 5.0.2 on 2024-03-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appointment1_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment1',
            name='patient_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
